In [62]:
# Run once only
#!pip install yfinance pandas numpy

# Income Objective Portfolio Construction (Bursa Malaysia)

Phase 1:
- Data collection
- Data cleaning
- Return computation
- Volatility classification (Stage 1 & Stage 2)

Benchmark: FTSE Bursa Malaysia KLCI

In [63]:
import yfinance as yf
import pandas as pd
import numpy as np
import os

# Fixed seed for reproducibility.
# The final stock selection is rules-based, but setting a seed supports reproducibility discipline.
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

## 1. Candidate Pool Selection

A diversified candidate pool of 40 Bursa Malaysia stocks is used. The pool includes a mix of sectors such as banking, utilities, healthcare, technology, plantation, industrials, energy, retail, and telecommunications.

This avoids manually pre-selecting only stable or risky stocks. Instead, volatility classification is allowed to emerge from the computed return and volatility statistics.

In [64]:
stocks = [
    "1155.KL","1295.KL","1023.KL","5347.KL","5225.KL",
    "5819.KL","1961.KL","2445.KL","3816.KL","6012.KL",
    "4863.KL","6888.KL","1082.KL","5183.KL","6033.KL",
    "1818.KL","4707.KL","4197.KL","3182.KL","4715.KL",
    "1066.KL","2488.KL","4677.KL","6742.KL","1562.KL",
    "5296.KL","7113.KL","7106.KL","5168.KL","6947.KL",
    "0138.KL","5216.KL","7277.KL","7084.KL","7203.KL",
    "5285.KL","5681.KL","1619.KL","5211.KL","0166.KL"
]

# In saved files, it will be renamed to "fbmklci" to match the assignment requirement.
benchmark = "^KLSE"

print(f"Candidate pool size: {len(stocks)} stocks")

Candidate pool size: 40 stocks

## 2. Data Collection

3 years of daily adjusted closing prices are downloaded using Yahoo Finance.

In [65]:
print("Downloading 3 years of daily adjusted closing prices...")

raw_data = yf.download(
    stocks + [benchmark],
    period="3y",
    auto_adjust=True,
    progress=True
)

# Extract closing prices only.
prices = raw_data["Close"].copy()

# Sort dates chronologically to ensure correct time-series ordering.
prices = prices.sort_index()

# Separate stock prices and benchmark prices.
stock_prices = prices.drop(columns=[benchmark]).copy()
benchmark_prices = prices[benchmark].copy()

# Rename benchmark to match assignment requirement.
benchmark_prices.name = "fbmklci"

print("Download completed.")
print(f"Raw stock price shape: {stock_prices.shape}")
print(f"Benchmark observations: {benchmark_prices.shape[0]}")

Downloading 3 years of daily adjusted closing prices...

[*********************100%***********************]  41 of 41 completed

Download completed.
Raw stock price shape: (741, 40)
Benchmark observations: 741

## 3. Data Cleaning and Alignment

Stocks with excessive missing values are removed using a 90% data availability threshold. This keeps the dataset reliable while avoiding unnecessary loss of diversification.

After cleaning, stock prices and FBMKLCI are aligned on the same trading dates.

In [66]:
minimum_required_observations = int(len(stock_prices) * 0.90)

stock_prices_clean = stock_prices.dropna(
    axis=1,
    thresh=minimum_required_observations
).copy()

# Combine cleaned stock prices with benchmark.
cleaned_prices = pd.concat([stock_prices_clean, benchmark_prices], axis=1)

# Drop rows where benchmark is missing.
cleaned_prices = cleaned_prices.dropna(subset=["fbmklci"])

# Forward filling is not used here because artificial prices may distort return and volatility estimates.
# Any remaining missing stock values will be handled during return calculation by dropping incomplete return rows.
print(f"Remaining stocks after cleaning: {len(stock_prices_clean.columns)}")
print(stock_prices_clean.columns.tolist())

print(f"\nCleaned price dataset shape including benchmark: {cleaned_prices.shape}")

Remaining stocks after cleaning: 40
['0138.KL', '0166.KL', '1023.KL', '1066.KL', '1082.KL', '1155.KL', '1295.KL', '1562.KL', '1619.KL', '1818.KL', '1961.KL', '2445.KL', '2488.KL', '3182.KL', '3816.KL', '4197.KL', '4677.KL', '4707.KL', '4715.KL', '4863.KL', '5168.KL', '5183.KL', '5211.KL', '5216.KL', '5225.KL', '5285.KL', '5296.KL', '5347.KL', '5681.KL', '5819.KL', '6012.KL', '6033.KL', '6742.KL', '6888.KL', '6947.KL', '7084.KL', '7106.KL', '7113.KL', '7203.KL', '7277.KL']

Cleaned price dataset shape including benchmark: (739, 41)

## 4. Log Return Calculation

Log returns are computed instead of simple percentage returns because the marking rubric expects log returns.

Formula:

\[
r_t = \ln\left(\frac{P_t}{P_{t-1}}\right)
\]

Log returns are suitable for statistical analysis because they are time-additive and commonly used in financial modelling.

In [67]:
# Separate cleaned stock prices and benchmark again after alignment.
stock_prices_clean = cleaned_prices.drop(columns=["fbmklci"])
benchmark_prices_clean = cleaned_prices["fbmklci"]

# Compute daily log returns.
returns = np.log(stock_prices_clean / stock_prices_clean.shift(1))
benchmark_returns = np.log(benchmark_prices_clean / benchmark_prices_clean.shift(1))

# Remove rows with missing values after log return calculation.
# This ensures all selected assets and the benchmark are aligned on identical dates.
returns = returns.dropna(how="any")
benchmark_returns = benchmark_returns.dropna()

# Align stocks and benchmark on common dates.
common_dates = returns.index.intersection(benchmark_returns.index)
returns = returns.loc[common_dates]
benchmark_returns = benchmark_returns.loc[common_dates]

# Combined return dataset for traceability.
returns_with_benchmark = pd.concat([returns, benchmark_returns.rename("fbmklci")], axis=1)

print(f"Stock log return dataset shape: {returns.shape}")
print(f"Benchmark log return observations: {benchmark_returns.shape[0]}")
print(f"Date range: {returns.index.min().date()} to {returns.index.max().date()}")

Stock log return dataset shape: (738, 40)
Benchmark log return observations: 738
Date range: 2023-05-16 to 2026-05-15

## 5. Daily Statistics

For each stock, the following statistics are computed:

- Mean Return: average daily log return
- Volatility: standard deviation of daily log returns
- Annual Return: daily mean return × 252
- Annual Risk: daily volatility × √252

These statistics support Stage 1 and Stage 2 volatility classification.

In [68]:
mean_returns = returns.mean()
volatility = returns.std()

stats_full = pd.DataFrame({
    "Mean Return": mean_returns,
    "Volatility": volatility,
    "Annual Return": mean_returns * 252,
    "Annual Risk": volatility * np.sqrt(252)
})

# Remove zero-volatility stocks to avoid division errors.
stats_full = stats_full[stats_full["Volatility"] > 0].copy()

# Supporting efficiency metric.
# This is not the main Stage 1 selection rule because the income objective prioritises stability.
stats_full["Return/Risk Ratio"] = stats_full["Mean Return"] / stats_full["Volatility"]

display(stats_full.head())

,Mean Return,Volatility,Annual Return,Annual Risk,Return/Risk Ratio
0138.KL,0.000188,0.024897,0.047463,0.395227,0.007565
0166.KL,-0.000047,0.027434,-0.011813,0.435496,-0.001709
1023.KL,0.000883,0.012708,0.222391,0.201728,0.069447
1066.KL,0.000826,0.008841,0.208046,0.140345,0.093382
1082.KL,0.000214,0.009926,0.053896,0.157568,0.021547

## 6. Stage 1: Low-Volatility Stock Selection

The assignment states that Stage 1 should contain 10 low-volatility stocks where:

(daily r̄p > daily σp) 

If fewer than 10 stocks satisfy the rule, a stabiliser is applied:
- keep only stocks with positive mean returns, and
- select the 10 stocks with the lowest volatility.

This stabiliser is consistent with the income objective because income portfolios prioritise positive return and stable risk.

In [69]:
# Income objective: Stage 1 should avoid negative-return assets.
stats_positive = stats_full[stats_full["Mean Return"] > 0].copy()

print(f"Stocks with positive mean returns: {len(stats_positive)}")
print(f"Stocks excluded due to negative mean returns: {len(stats_full) - len(stats_positive)}")

# Step 1: Try the strict assignment condition.
low_vol_condition = stats_positive[
    stats_positive["Mean Return"] > stats_positive["Volatility"]
].copy()

print(f"Stocks satisfying strict Stage 1 rule (Mean Return > Volatility): {len(low_vol_condition)}")

# Step 2: Apply selection logic.
if len(low_vol_condition) >= 10:
    low_vol = low_vol_condition.sort_values(
        by="Volatility",
        ascending=True
    ).head(10).copy()
    
    low_vol_method = "Strict assignment rule: Mean Return > Volatility"

else:
    print("Fewer than 10 stocks met the strict Stage 1 rule.")
    print("Applying stabiliser: positive-return stocks with lowest volatility.")
    
    low_vol = stats_positive.sort_values(
        by="Volatility",
        ascending=True
    ).head(10).copy()
    
    low_vol_method = "Stabiliser: positive-return stocks with lowest volatility"

low_vol["Selection Method"] = low_vol_method

print("\nStage 1 Low-Volatility Stocks:")
display(low_vol[["Mean Return", "Volatility", "Annual Return", "Annual Risk", "Return/Risk Ratio"]])

Stocks with positive mean returns: 24
Stocks excluded due to negative mean returns: 16
Stocks satisfying strict Stage 1 rule (Mean Return > Volatility): 0
Fewer than 10 stocks met the strict Stage 1 rule.
Applying stabiliser: positive-return stocks with lowest volatility.

Stage 1 Low-Volatility Stocks:

,Mean Return,Volatility,Annual Return,Annual Risk,Return/Risk Ratio
1155.KL,0.000577,0.007774,0.145356,0.123414,0.074194
1066.KL,0.000826,0.008841,0.208046,0.140345,0.093382
5819.KL,0.000289,0.009315,0.072749,0.147864,0.030993
6033.KL,0.000274,0.009541,0.068953,0.151465,0.028677
5225.KL,0.000656,0.009658,0.165269,0.153320,0.067903
1082.KL,0.000214,0.009926,0.053896,0.157568,0.021547
1818.KL,0.000635,0.010283,0.160046,0.163244,0.061760
1295.KL,0.000488,0.010373,0.123058,0.164672,0.047075
5347.KL,0.000733,0.010735,0.184718,0.170420,0.068279
3816.KL,0.000363,0.010773,0.091381,0.171016,0.033661

## 7. Stage 2: High-Volatility Stock Selection

The assignment states that Stage 2 should add 5 high-volatility stocks where:

(daily σp > 3.0  of daily r̄p ) 

The full stock universe is used for this rule because Stage 2 is designed to test the effect of adding riskier stocks, including stocks with weak or negative recent performance.

In [70]:
high_vol_candidates = stats_full[
    stats_full["Volatility"] > 3 * stats_full["Mean Return"]
].copy()

print(f"Stocks satisfying Stage 2 high-volatility rule: {len(high_vol_candidates)}")

# If enough stocks satisfy the condition, choose the five with highest volatility.
# This ensures the Stage 2 addition truly represents a high-volatility regime.
if len(high_vol_candidates) >= 5:
    high_vol = high_vol_candidates.sort_values(
        by="Volatility",
        ascending=False
    ).head(5).copy()
    
    high_vol_method = "Assignment rule: Volatility > 3 × Mean Return"

else:
    print("⚠️ Fewer than 5 stocks met the high-volatility rule.")
    print("Applying stabiliser: selecting highest-volatility stocks from full universe.")
    
    high_vol = stats_full.sort_values(
        by="Volatility",
        ascending=False
    ).head(5).copy()
    
    high_vol_method = "Stabiliser: highest-volatility stocks"

high_vol["Meets High-Vol Rule"] = high_vol["Volatility"] > 3 * high_vol["Mean Return"]
high_vol["Selection Method"] = high_vol_method

print("\nStage 2 High-Volatility Additions:")
display(high_vol[["Mean Return", "Volatility", "Annual Return", "Annual Risk", "Return/Risk Ratio", "Meets High-Vol Rule"]])

negative_high_vol = high_vol[high_vol["Mean Return"] < 0]

if len(negative_high_vol) > 0:
    print("\nImportant note: Some Stage 2 high-volatility stocks have negative mean returns:")
    print(negative_high_vol.index.tolist())

Stocks satisfying Stage 2 high-volatility rule: 40

Stage 2 High-Volatility Additions:

,Mean Return,Volatility,Annual Return,Annual Risk,Return/Risk Ratio,Meets High-Vol Rule
5168.KL,-0.000706,0.032474,-0.177817,0.515514,-0.021729,True
5216.KL,-0.000388,0.030716,-0.097891,0.487604,-0.012647,True
7113.KL,-0.000392,0.030123,-0.098781,0.478185,-0.013013,True
4677.KL,0.001680,0.029546,0.423448,0.469031,0.056872,True
7106.KL,-0.001071,0.027472,-0.269787,0.436104,-0.038970,True

Important note: Some Stage 2 high-volatility stocks have negative mean returns:
['5168.KL', '5216.KL', '7113.KL', '7106.KL']

## 8. Final Selected Universes

- Stage 1 contains 10 low-volatility stocks.

- Stage 2 contains the Stage 1 stocks plus 5 high-volatility additions.

These two universes will be used in the next phase for annual return, annual risk, beta, Sharpe ratio, and portfolio optimisation.

In [71]:
stage1_stocks = list(low_vol.index)
stage2_additions = list(high_vol.index)
stage2_stocks = stage1_stocks + stage2_additions

selected_stocks = stage2_stocks

print("Stage 1 Low-Volatility Universe:")
print(stage1_stocks)

print("\nStage 2 High-Volatility Additions:")
print(stage2_additions)

print("\nStage 2 Full Universe:")
print(stage2_stocks)

print(f"\nStage 1 size: {len(stage1_stocks)}")
print(f"Stage 2 size: {len(stage2_stocks)}")

Stage 1 Low-Volatility Universe:
['1155.KL', '1066.KL', '5819.KL', '6033.KL', '5225.KL', '1082.KL', '1818.KL', '1295.KL', '5347.KL', '3816.KL']

Stage 2 High-Volatility Additions:
['5168.KL', '5216.KL', '7113.KL', '4677.KL', '7106.KL']

Stage 2 Full Universe:
['1155.KL', '1066.KL', '5819.KL', '6033.KL', '5225.KL', '1082.KL', '1818.KL', '1295.KL', '5347.KL', '3816.KL', '5168.KL', '5216.KL', '7113.KL', '4677.KL', '7106.KL']

Stage 1 size: 10
Stage 2 size: 15

## 9. Export Phase 1 Outputs

The following files are saved for reproducibility and for use in later phases:

- Candidate pool
- Cleaned price dataset
- Log return dataset
- Benchmark log returns
- Stock statistics
- Stage 1 selected stocks
- Stage 2 selected stocks
- Stage 1 and Stage 2 return datasets

In [72]:
OVERWRITE_OUTPUT = True

if OVERWRITE_OUTPUT:
    os.makedirs("output", exist_ok=True)

    # Candidate pool
    pd.Series(stocks, name="Candidate Pool").to_csv(
        "output/candidate_pool.csv",
        index=False
    )

    # Cleaned daily closing prices including benchmark labelled as fbmklci
    cleaned_prices.to_csv("output/cleaned_prices_with_fbmklci.csv")

    # Log returns
    returns.to_csv("output/log_returns.csv")
    benchmark_returns.rename("fbmklci").to_csv("output/fbmklci_log_returns.csv")
    returns_with_benchmark.to_csv("output/log_returns_with_fbmklci.csv")

    # Statistics and filtering outputs
    stats_full.to_csv("output/stock_statistics_full.csv")
    low_vol.to_csv("output/stage1_low_vol_stocks.csv")
    high_vol.to_csv("output/stage2_high_vol_additions.csv")

    # Selected stock lists
    pd.Series(stage1_stocks, name="Stage 1 Stocks").to_csv(
        "output/stage1_stocks.csv",
        index=False
    )

    pd.Series(stage2_additions, name="Stage 2 Additions").to_csv(
        "output/stage2_additions.csv",
        index=False
    )

    pd.Series(stage2_stocks, name="Stage 2 Full Universe").to_csv(
        "output/stage2_stocks.csv",
        index=False
    )

    # Return datasets for next phase
    returns_stage1 = returns[stage1_stocks].copy()
    returns_stage2 = returns[stage2_stocks].copy()

    returns_stage1.to_csv("output/log_returns_stage1.csv")
    returns_stage2.to_csv("output/log_returns_stage2.csv")

    print("✅ Phase 1 outputs saved successfully.")
    print("Saved files in /output folder.")

else:
    print("Output saving skipped. Set OVERWRITE_OUTPUT = True to save files.")

✅ Phase 1 outputs saved successfully.
Saved files in /output folder.

## 10. Raw Individual Stock Data Export

Run only once for dataset generation.

In [73]:
SAVE_RAW_DATA = False

if SAVE_RAW_DATA:
    os.makedirs("raw_data", exist_ok=True)

    for ticker in stock_prices_clean.columns:
        individual_df = stock_prices_clean[[ticker]].dropna()
        individual_df.to_csv(f"raw_data/{ticker}.csv")

    benchmark_prices_clean.rename("fbmklci").to_csv("raw_data/fbmklci.csv")

    print("✅ Raw individual stock files saved in /raw_data folder.")

else:
    print("Raw data export skipped.")

Raw data export skipped.

## 11. Filtering out the returns to align with the selected stocks

In [74]:
sls = pd.read_csv("output/selected_stocks.csv")
selected = sls["Selected Stocks"].dropna().astype(str).tolist()

# 2) Load returns (first column is the date index)
not_filtered_returns = pd.read_csv("output/returns.csv", index_col=0)

# 3) Filter to selected columns that exist
selected_existing = [t for t in selected if t in not_filtered_returns.columns]
missing = sorted(set(selected) - set(selected_existing))
if missing:
    print(f"Missing from returns.csv ({len(missing)}): {missing}")

returns_selected = returns.loc[:, selected_existing]

# 4) Save + preview

** Save and preview filtered returns**

In [75]:
returns_selected.to_csv("output/returns_selected.csv")
returns_selected.head()

,1155.KL,1066.KL,5819.KL,5225.KL,1082.KL,6033.KL,1961.KL,1818.KL,1295.KL,5347.KL,5168.KL,5216.KL,7113.KL,5183.KL,0166.KL
Date,,,,,,,,,,,,,,,
2023-05-16,0.004593,0.001816,-0.004012,0.001691,0.006719,0.001190,0.012903,-0.004835,0.002535,0.021819,0.013423,-0.011835,0.028171,0.012812,0.018349
2023-05-17,-0.002294,0.000000,-0.003020,-0.003384,-0.013484,0.004745,0.015267,-0.003236,0.002528,0.002053,0.051960,0.011835,0.027399,-0.012812,-0.004556
2023-05-18,0.005724,-0.001816,0.007032,0.008439,0.001131,0.001183,0.010050,0.009678,0.002522,0.004094,0.122927,0.011696,0.052644,0.004289,0.004556
2023-05-19,0.002281,0.000000,0.000000,0.000000,0.020135,0.009412,0.000000,0.001604,0.002516,0.003060,-0.034159,0.000000,0.025318,-0.021630,0.004535
2023-05-22,-0.023043,0.000000,0.000000,0.001679,-0.014501,-0.005872,0.000000,0.019048,-0.007566,-0.022658,-0.015564,0.000000,0.016529,0.014472,0.000000

## 12. Calculating the correlation of stocks

In [76]:
filtered_returns = pd.read_csv("output/returnsmergedFMBKLCI.csv")

df = filtered_returns.drop(columns=["Date","Num"])


correlation_matrix = df.corr()
print("Correlation Matrix Across Stocks:")
print(correlation_matrix.round(3))

KeyError: "['Num'] not found in axis"

## 13. Calculating Beta

**13.1 Merge FMBKLCI return with stock returns**

In [ ]:
benchmark_returns.to_csv("output/KLCIreturn.csv")## save bechmark return get from previous codes
##read both files with returns
klci= pd.read_csv("output/KLCIreturn.csv")
filtered_returns=pd.read_csv("output/returns_selected.csv")
##merge both files with prices inner join with dates
merged = pd.merge(filtered_returns,klci, on="Date", how="inner")

## save files for further calculations
merged.to_csv("output/returnsmergedFMBKLCI.csv")

**13.2 Beta calculation**

In [ ]:
# Compute full covariance matrix
returns_merged = pd.read_csv("output/returnsmergedFMBKLCI.csv").drop(columns=["Date","Num"])
cov_matrix = returns_merged.cov()

cov_matrix.to_csv("output/Covariance_Matrix.csv")

# Market variance
market_var = cov_matrix.loc['^KLSE', '^KLSE']

# Beta = Cov(stock, market) / Var(market)
beta = cov_matrix['^KLSE'] / market_var

# Remove market itself
beta = beta.drop('^KLSE')
beta.to_csv("output/beta.csv")

# Display
print("Beta for each stocks againts FMBKLCI:")
print(beta.round(3))

KeyError: "['Num'] not found in axis"

## 14. Calculating Shape Ratio for each stock and form the TABLE

In [ ]:


readdata = pd.read_csv('output/Combinedvolatality.csv')#thiss file has different order of tickers 
#sorting
readStocks = pd.read_csv('output/selected_stocks.csv')#sort 
order = readStocks["Selected Stocks"].tolist()
readdata_sorted = readdata.set_index("Ticker").loc[order].reset_index()

#function
def sharpe_ratio_stock(meanreturn, riskfree, volatility):

    result = ((meanreturn - riskfree)) / volatility
    return result



readdata_sorted['BetaversusFMBKLCI'] = readdata_sorted['Ticker'].map(beta)## map the beta result to tickers in file

Rf = 0.03/252## daily risk-free rate
readdata_sorted ['SharpeRatio'] = readdata_sorted .apply(
    lambda row: sharpe_ratio_stock(
        row.iloc[1],   # mean return column
        Rf,
        row.iloc[2]    # volatility column
    ),
    axis=1


)##### insert the Sharpe ratio of each stock into table or we can array



# Save to CSV (sorted rows + beta + Sharpe)
readdata_sorted.to_csv(
    'output/TabulatedDataResult.csv',
    index=False
)

print(readdata_sorted)

     Ticker  Mean Return  Volatility  Annual Return  Annual Risk  \
0   1155.KL     0.000541    0.008801       0.136381     0.139714
1   1066.KL     0.001144    0.010205       0.288231     0.161996
2   5819.KL     0.000509    0.010455       0.128188     0.165963
3   5225.KL     0.000765    0.010677       0.192771     0.169497
4   1082.KL     0.000464    0.010704       0.117013     0.169923
5   6033.KL     0.000228    0.010783       0.057347     0.171179
6   1961.KL     0.000267    0.010805       0.067270     0.171527
7   1818.KL     0.000544    0.011517       0.136962     0.182821
8   1295.KL     0.000510    0.011619       0.128504     0.184452
9   5347.KL     0.000632    0.011703       0.159319     0.185774
10  5168.KL    -0.001144    0.036233      -0.288366     0.575177
11  5216.KL    -0.000045    0.035685      -0.011250     0.566490
12  7113.KL     0.000108    0.032951       0.027217     0.523086
13  5183.KL     0.000119    0.031934       0.029932     0.506932
14  0166.KL    -0.000254    0.031317      -0.064128     0.497136

    Return/Risk Ratio  BetaversusFMBKLCI  SharpeRatio
0            0.061491           0.865092     0.047965
1            0.112082           0.828580     0.100416
2            0.048656           0.823520     0.037269
3            0.071644           0.562545     0.060495
4            0.043379           0.740557     0.032257
5            0.021104           0.561978     0.010064
6            0.024705           0.508625     0.013688
7            0.047193           0.732770     0.036856
8            0.043887           1.079614     0.033641
9            0.054023           0.938395     0.043851
10          -0.031582           1.163880    -0.034868
11          -0.001251           0.991963    -0.004587
12           0.003278           0.949212    -0.000335
13           0.003719           1.227579    -0.000009
14          -0.008126           1.980358    -0.011927

## 15. Weighting stocks for portfolio and sharpe ratio

Read selected stocks for weighting

In [ ]:
readStocks = pd.read_csv('output/selected_stocks.csv')
tickers = readStocks.iloc[:, 1] .tolist()

 14. 1 Equal Weighting

In [ ]:

##Equal weighting##
n= len(tickers)
eqweight = 1.0/n


equal_weight = {ticker:eqweight for ticker in tickers }
weight_series = pd.Series(equal_weight)

print(weight_series)


# weight_series sums to 1; index is ticker

1155.KL    0.066667
1066.KL    0.066667
5819.KL    0.066667
5225.KL    0.066667
1082.KL    0.066667
6033.KL    0.066667
1961.KL    0.066667
1818.KL    0.066667
1295.KL    0.066667
5347.KL    0.066667
5168.KL    0.066667
5216.KL    0.066667
7113.KL    0.066667
5183.KL    0.066667
0166.KL    0.066667
dtype: float64

14.1.1 equal weight portfolio (daily)

In [ ]:
#returns
stocksreturns=pd.read_csv("output/returnsmergedFMBKLCI.csv").drop(columns=["^KLSE","Num"])
meansreturn = stocksreturns.mean(numeric_only=True)

cov = stocksreturns.cov(numeric_only=True)##covaraince of stock return

eqportfolio_return = np.dot(weight_series,meansreturn)## portfolio return



eq_portfolio_volatility = np.sqrt(
    np.dot(weight_series.T, np.dot(cov, weight_series))
)## volatility

Rf#defined abv when calculating stocks sharpe ratio

eq_sharpe_ratio = (eqportfolio_return - Rf) / eq_portfolio_volatility##sharpe ratio portfolio

print("return")
print(eqportfolio_return)
print("volatility")
print(eq_portfolio_volatility)
print("sharpe ratio")
print(eq_sharpe_ratio)

return
0.00025840765483904285
volatility
0.008998557935242655
sharpe ratio
0.015486929883023064

14.1.1.2 equal weight with sharpe ratio (annual)

In [ ]:
annual_return = eqportfolio_return * 252
annual_volatility = eq_portfolio_volatility * np.sqrt(252)
annual_sharpe = (annual_return - 0.03) / annual_volatility

print("return")
print(annual_return)
print("volatility")
print(annual_volatility)
print("sharpe ratio")
print(annual_sharpe)

return
0.0651187290194388
volatility
0.14284767872915358
sharpe ratio
0.24584739025424196

14.2 weight by volatality

Sort volatality for observation

In [ ]:
combined = pd.read_csv("output/Combinedvolatality.csv")

order = readStocks["Selected Stocks"].tolist()
combined_sorted = combined.set_index("Ticker").loc[order].reset_index()## sort by stocks

sortbyvol = combined.sort_values("Volatility", ascending=True)
print("#####################")
print(combined_sorted)###sort vol for observation
print("#####################")

#####################
     Ticker  Mean Return  Volatility  Annual Return  Annual Risk  \
0   1155.KL     0.000541    0.008801       0.136381     0.139714
1   1066.KL     0.001144    0.010205       0.288231     0.161996
2   5819.KL     0.000509    0.010455       0.128188     0.165963
3   5225.KL     0.000765    0.010677       0.192771     0.169497
4   1082.KL     0.000464    0.010704       0.117013     0.169923
5   6033.KL     0.000228    0.010783       0.057347     0.171179
6   1961.KL     0.000267    0.010805       0.067270     0.171527
7   1818.KL     0.000544    0.011517       0.136962     0.182821
8   1295.KL     0.000510    0.011619       0.128504     0.184452
9   5347.KL     0.000632    0.011703       0.159319     0.185774
10  5168.KL    -0.001144    0.036233      -0.288366     0.575177
11  5216.KL    -0.000045    0.035685      -0.011250     0.566490
12  7113.KL     0.000108    0.032951       0.027217     0.523086
13  5183.KL     0.000119    0.031934       0.029932     0.506932
14  0166.KL    -0.000254    0.031317      -0.064128     0.497136

    Return/Risk Ratio
0            0.061491
1            0.112082
2            0.048656
3            0.071644
4            0.043379
5            0.021104
6            0.024705
7            0.047193
8            0.043887
9            0.054023
10          -0.031582
11          -0.001251
12           0.003278
13           0.003719
14          -0.008126
#####################

- 14.2.1  inverse weighting

In [ ]:
inv_vol = 1.0 / sortbyvol["Volatility"]### weight goes smaller as vol goes bigger
weights = inv_vol / inv_vol.sum()### change the weight into propotion\n",
inverse_weighting = pd.Series(weights.values, index=sortbyvol["Ticker"].values)


print("###############")
print(inverse_weighting)## inverse weight

###############
1155.KL    0.104509
1066.KL    0.090134
5819.KL    0.087980
5225.KL    0.086146
1082.KL    0.085929
6033.KL    0.085299
1961.KL    0.085126
1818.KL    0.079867
1295.KL    0.079161
5347.KL    0.078598
0166.KL    0.029371
5183.KL    0.028804
7113.KL    0.027914
5216.KL    0.025775
5168.KL    0.025386
dtype: float64

14.2.1.1 inverse weight portfolio sharpe  (daily)

In [ ]:
##cov is defined abv
##meansreturn defined abv

inv_portfolio_return = np.dot(inverse_weighting,meansreturn)## portfolio return

inv_portfolio_volatility = np.sqrt(
    np.dot(inverse_weighting.T, np.dot(cov,inverse_weighting ))
)## volatility

Rf#defined abv when calculating stocks sharpe ratio

inv_sharpe_ratio = (inv_portfolio_return - Rf) / inv_portfolio_volatility##sharpe ratio portfolio

print("return")
print(inv_portfolio_return)
print("volatility")
print(inv_portfolio_volatility)
print("sharpe ratio")
print(inv_sharpe_ratio)# 0.04404861148026879

return
0.00041907985415850916
volatility
0.006811389168198572
sharpe ratio
0.04404861148026879

14.2.1.2 inverse weight portfolio (annual)

In [ ]:
annual_return = inv_portfolio_return * 252
annual_volatility = inv_portfolio_volatility * np.sqrt(252)
annual_sharpe = (annual_return - 0.03) / annual_volatility


print("return")
print(annual_return)
print("volatility")
print(annual_volatility)
print("sharpe ratio")
print(annual_sharpe)

return
0.1056081232479443
volatility
0.10812745093159515
sharpe ratio
0.6992500294469755

- 14.2.2 weight ascending to volatality

In [ ]:
asc_vol = sortbyvol["Volatility"]### weight goes smaller as vol goes bigger
weights = asc_vol / asc_vol.sum()### change the weight into propotion\n",
asc_weighting = pd.Series(weights.values, index=sortbyvol["Ticker"].values)


print("###############")
print(asc_weighting)## inverse weight

###############
1155.KL    0.031959
1066.KL    0.037056
5819.KL    0.037963
5225.KL    0.038772
1082.KL    0.038869
6033.KL    0.039156
1961.KL    0.039236
1818.KL    0.041819
1295.KL    0.042193
5347.KL    0.042495
0166.KL    0.113718
5183.KL    0.115958
7113.KL    0.119654
5216.KL    0.129582
5168.KL    0.131569
dtype: float64

14.2.2.1 ascending weighting portfolio (daily)

In [ ]:
asc_portfolio_return = np.dot(asc_weighting,meansreturn)## portfolio return

asc_portfolio_volatility = np.sqrt(
    np.dot(inverse_weighting.T, np.dot(cov,asc_weighting ))
)## volatility

Rf#defined abv when calculating stocks sharpe ratio

asc_sharpe_ratio = (asc_portfolio_return - Rf) / asc_portfolio_volatility##sharpe ratio portfolio

print(asc_sharpe_ratio)### -0.009283002913153251

-0.009283002913153251

14.2.2.2 asceding weighting portfolio (annual)

In [ ]:
annual_return = asc_portfolio_return * 252
annual_volatility = asc_portfolio_volatility * np.sqrt(252)
annual_sharpe = (annual_return - 0.03) / annual_volatility

print("return")
print(annual_return)
print("volatility")
print(annual_volatility)
print("sharpe ratio")
print(annual_sharpe)

return
0.010390630343710967
volatility
0.1330683820297116
sharpe ratio
-0.14736310276854975